# Generated by Django 5.2.4 on 2025-07-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0006_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='application',
            name='video_resume',
            field=models.FileField(blank=True, null=True, upload_to='video_resumes/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Applied', 'Applied'), ('Reviewed', 'Reviewed'), ('Interview', 'Interview'), ('Offered', 'Offered'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
