# Generated by Django 5.2.4 on 2025-07-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0007_application_sentiment_score_application_video_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='sentiment_score',
        ),
        migrations.AddField(
            model_name='application',
            name='ai_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
